-- 0008_correlation_idempotency (Phase 2.3): make re-planning idempotent.
--
-- A correlation proposal's identity is the (ask, work item) pair: the
-- reply-target message (source + native id) and the Jira issue key. Storing that
-- key lets a re-plan cycle SKIP re-queueing a proposal that already exists in a
-- decided-or-open state (proposed / approved / executed / execution_failed /
-- rejected) — so repeated `correlate` runs never duplicate, a human's rejection
-- is never resurrected by the next cycle, and a later commit adding MORE evidence
-- to the same ask+issue does not mint a second, duplicate-looking proposal (the
-- evidence set is intentionally NOT part of the identity). EXPIRED proposals do
-- NOT block: they lapsed without a decision, so re-planning may re-surface them.
--
-- Nullable — dev-seeded and pre-2.3 proposals carry no key. Plain ADD COLUMN
-- (no CHECK change → no table rebuild). Shipped migrations are not edited.
ALTER TABLE action_proposals ADD COLUMN correlation_key TEXT;
